/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CL_H_RPCGEN
#define _CL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct cl_msg_t_s {
	short addr;
	short flags;
	int len;
};
typedef struct cl_msg_t_s cl_msg_t_s;


struct cl_bus_t_s {
	int info;
	int src;
	int dst;
	int length;
	int stride;
	int next;
};
typedef struct cl_bus_t_s cl_bus_t_s;


struct cl_calc_freq_req {
	int __in10;
	int __in;
};
typedef struct cl_calc_freq_req cl_calc_freq_req;


struct cl_calc_freq_res_t {
	u_int __out;
};
typedef struct cl_calc_freq_res_t cl_calc_freq_res_t;


struct cl_calc_freq_res {
	int errcode;
	union {
		cl_calc_freq_res_t __res;
	} cl_calc_freq_res_u;
};
typedef struct cl_calc_freq_res cl_calc_freq_res;

struct cl_calc_alert_req {
	int __in10;
	int __in;
	u_int __inout;
};
typedef struct cl_calc_alert_req cl_calc_alert_req;


struct cl_calc_alert_res_t {
	u_int __inout;
};
typedef struct cl_calc_alert_res_t cl_calc_alert_res_t;


struct cl_calc_alert_res {
	int errcode;
	union {
		cl_calc_alert_res_t __res;
	} cl_calc_alert_res_u;
};
typedef struct cl_calc_alert_res cl_calc_alert_res;

struct cl_calc_read_req {
	short __in10;
	u_short __in;
};
typedef struct cl_calc_read_req cl_calc_read_req;


struct cl_calc_read_res_t {
	u_int __out;
};
typedef struct cl_calc_read_res_t cl_calc_read_res_t;


struct cl_calc_read_res {
	int errcode;
	union {
		cl_calc_read_res_t __res;
	} cl_calc_read_res_u;
};
typedef struct cl_calc_read_res cl_calc_read_res;

struct cl_calc_write_req {
	cl_msg_t_s __in;
};
typedef struct cl_calc_write_req cl_calc_write_req;


struct cl_calc_write_res_t {
	cl_bus_t_s __out;
};
typedef struct cl_calc_write_res_t cl_calc_write_res_t;


struct cl_calc_write_res {
	int errcode;
	union {
		cl_calc_write_res_t __res;
	} cl_calc_write_res_u;
};
typedef struct cl_calc_write_res cl_calc_write_res;

struct cl_calc_timer_req {
	cl_msg_t_s __in;
};
typedef struct cl_calc_timer_req cl_calc_timer_req;


struct cl_calc_timer_res_t {
	cl_bus_t_s __out;
};
typedef struct cl_calc_timer_res_t cl_calc_timer_res_t;


struct cl_calc_timer_res {
	int errcode;
	union {
		cl_calc_timer_res_t __res;
	} cl_calc_timer_res_u;
};
typedef struct cl_calc_timer_res cl_calc_timer_res;

struct cl_calc_filter_req {
	cl_msg_t_s __in;
};
typedef struct cl_calc_filter_req cl_calc_filter_req;


struct cl_calc_filter_res_t {
	cl_bus_t_s __out;
};
typedef struct cl_calc_filter_res_t cl_calc_filter_res_t;


struct cl_calc_filter_res {
	int errcode;
	union {
		cl_calc_filter_res_t __res;
	} cl_calc_filter_res_u;
};
typedef struct cl_calc_filter_res cl_calc_filter_res;

struct cl_calc_serial_req {
	cl_msg_t_s __in1;
	cl_msg_t_s __in2;
};
typedef struct cl_calc_serial_req cl_calc_serial_req;


struct cl_calc_serial_res_t {
	cl_bus_t_s __out;
};
typedef struct cl_calc_serial_res_t cl_calc_serial_res_t;


struct cl_calc_serial_res {
	int errcode;
	union {
		cl_calc_serial_res_t __res;
	} cl_calc_serial_res_u;
};
typedef struct cl_calc_serial_res cl_calc_serial_res;

struct cl_calc_servo_req {
	cl_msg_t_s __inout;
};
typedef struct cl_calc_servo_req cl_calc_servo_req;


struct cl_calc_servo_res_t {
	cl_msg_t_s __inout;
	cl_bus_t_s __out;
};
typedef struct cl_calc_servo_res_t cl_calc_servo_res_t;


struct cl_calc_servo_res {
	int errcode;
	union {
		cl_calc_servo_res_t __res;
	} cl_calc_servo_res_u;
};
typedef struct cl_calc_servo_res cl_calc_servo_res;

struct cl_calc_set_req {
	short __in1;
	u_int __in2;
};
typedef struct cl_calc_set_req cl_calc_set_req;


struct cl_calc_set_res_t {
	u_short __out;
};
typedef struct cl_calc_set_res_t cl_calc_set_res_t;


struct cl_calc_set_res {
	int errcode;
	union {
		cl_calc_set_res_t __res;
	} cl_calc_set_res_u;
};
typedef struct cl_calc_set_res cl_calc_set_res;

#define CLPROG 0x20000001
#define CLVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CL_CALC_FREQ_FUNC 1
extern  cl_calc_freq_res * cl_calc_freq_func_1(cl_calc_freq_req *, CLIENT *);
extern  cl_calc_freq_res * cl_calc_freq_func_1_svc(cl_calc_freq_req *, struct svc_req *);
#define CL_CALC_ALERT_FUNC 2
extern  cl_calc_alert_res * cl_calc_alert_func_1(cl_calc_alert_req *, CLIENT *);
extern  cl_calc_alert_res * cl_calc_alert_func_1_svc(cl_calc_alert_req *, struct svc_req *);
#define CL_CALC_READ_FUNC 3
extern  cl_calc_read_res * cl_calc_read_func_1(cl_calc_read_req *, CLIENT *);
extern  cl_calc_read_res * cl_calc_read_func_1_svc(cl_calc_read_req *, struct svc_req *);
#define CL_CALC_WRITE_FUNC 4
extern  cl_calc_write_res * cl_calc_write_func_1(cl_calc_write_req *, CLIENT *);
extern  cl_calc_write_res * cl_calc_write_func_1_svc(cl_calc_write_req *, struct svc_req *);
#define CL_CALC_TIMER_FUNC 5
extern  cl_calc_timer_res * cl_calc_timer_func_1(cl_calc_timer_req *, CLIENT *);
extern  cl_calc_timer_res * cl_calc_timer_func_1_svc(cl_calc_timer_req *, struct svc_req *);
#define CL_CALC_FILTER_FUNC 6
extern  cl_calc_filter_res * cl_calc_filter_func_1(cl_calc_filter_req *, CLIENT *);
extern  cl_calc_filter_res * cl_calc_filter_func_1_svc(cl_calc_filter_req *, struct svc_req *);
#define CL_CALC_SERIAL_FUNC 7
extern  cl_calc_serial_res * cl_calc_serial_func_1(cl_calc_serial_req *, CLIENT *);
extern  cl_calc_serial_res * cl_calc_serial_func_1_svc(cl_calc_serial_req *, struct svc_req *);
#define CL_CALC_SERVO_FUNC 8
extern  cl_calc_servo_res * cl_calc_servo_func_1(cl_calc_servo_req *, CLIENT *);
extern  cl_calc_servo_res * cl_calc_servo_func_1_svc(cl_calc_servo_req *, struct svc_req *);
#define CL_CALC_SET_FUNC 9
extern  cl_calc_set_res * cl_calc_set_func_1(cl_calc_set_req *, CLIENT *);
extern  cl_calc_set_res * cl_calc_set_func_1_svc(cl_calc_set_req *, struct svc_req *);
extern int clprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CL_CALC_FREQ_FUNC 1
extern  cl_calc_freq_res * cl_calc_freq_func_1();
extern  cl_calc_freq_res * cl_calc_freq_func_1_svc();
#define CL_CALC_ALERT_FUNC 2
extern  cl_calc_alert_res * cl_calc_alert_func_1();
extern  cl_calc_alert_res * cl_calc_alert_func_1_svc();
#define CL_CALC_READ_FUNC 3
extern  cl_calc_read_res * cl_calc_read_func_1();
extern  cl_calc_read_res * cl_calc_read_func_1_svc();
#define CL_CALC_WRITE_FUNC 4
extern  cl_calc_write_res * cl_calc_write_func_1();
extern  cl_calc_write_res * cl_calc_write_func_1_svc();
#define CL_CALC_TIMER_FUNC 5
extern  cl_calc_timer_res * cl_calc_timer_func_1();
extern  cl_calc_timer_res * cl_calc_timer_func_1_svc();
#define CL_CALC_FILTER_FUNC 6
extern  cl_calc_filter_res * cl_calc_filter_func_1();
extern  cl_calc_filter_res * cl_calc_filter_func_1_svc();
#define CL_CALC_SERIAL_FUNC 7
extern  cl_calc_serial_res * cl_calc_serial_func_1();
extern  cl_calc_serial_res * cl_calc_serial_func_1_svc();
#define CL_CALC_SERVO_FUNC 8
extern  cl_calc_servo_res * cl_calc_servo_func_1();
extern  cl_calc_servo_res * cl_calc_servo_func_1_svc();
#define CL_CALC_SET_FUNC 9
extern  cl_calc_set_res * cl_calc_set_func_1();
extern  cl_calc_set_res * cl_calc_set_func_1_svc();
extern int clprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_cl_msg_t_s (XDR *, cl_msg_t_s*);
extern  bool_t xdr_cl_msg_t_s (XDR *, cl_msg_t_s*);
extern  bool_t xdr_cl_bus_t_s (XDR *, cl_bus_t_s*);
extern  bool_t xdr_cl_bus_t_s (XDR *, cl_bus_t_s*);
extern  bool_t xdr_cl_calc_freq_req (XDR *, cl_calc_freq_req*);
extern  bool_t xdr_cl_calc_freq_req (XDR *, cl_calc_freq_req*);
extern  bool_t xdr_cl_calc_freq_res_t (XDR *, cl_calc_freq_res_t*);
extern  bool_t xdr_cl_calc_freq_res_t (XDR *, cl_calc_freq_res_t*);
extern  bool_t xdr_cl_calc_freq_res (XDR *, cl_calc_freq_res*);
extern  bool_t xdr_cl_calc_alert_req (XDR *, cl_calc_alert_req*);
extern  bool_t xdr_cl_calc_alert_req (XDR *, cl_calc_alert_req*);
extern  bool_t xdr_cl_calc_alert_res_t (XDR *, cl_calc_alert_res_t*);
extern  bool_t xdr_cl_calc_alert_res_t (XDR *, cl_calc_alert_res_t*);
extern  bool_t xdr_cl_calc_alert_res (XDR *, cl_calc_alert_res*);
extern  bool_t xdr_cl_calc_read_req (XDR *, cl_calc_read_req*);
extern  bool_t xdr_cl_calc_read_req (XDR *, cl_calc_read_req*);
extern  bool_t xdr_cl_calc_read_res_t (XDR *, cl_calc_read_res_t*);
extern  bool_t xdr_cl_calc_read_res_t (XDR *, cl_calc_read_res_t*);
extern  bool_t xdr_cl_calc_read_res (XDR *, cl_calc_read_res*);
extern  bool_t xdr_cl_calc_write_req (XDR *, cl_calc_write_req*);
extern  bool_t xdr_cl_calc_write_req (XDR *, cl_calc_write_req*);
extern  bool_t xdr_cl_calc_write_res_t (XDR *, cl_calc_write_res_t*);
extern  bool_t xdr_cl_calc_write_res_t (XDR *, cl_calc_write_res_t*);
extern  bool_t xdr_cl_calc_write_res (XDR *, cl_calc_write_res*);
extern  bool_t xdr_cl_calc_timer_req (XDR *, cl_calc_timer_req*);
extern  bool_t xdr_cl_calc_timer_req (XDR *, cl_calc_timer_req*);
extern  bool_t xdr_cl_calc_timer_res_t (XDR *, cl_calc_timer_res_t*);
extern  bool_t xdr_cl_calc_timer_res_t (XDR *, cl_calc_timer_res_t*);
extern  bool_t xdr_cl_calc_timer_res (XDR *, cl_calc_timer_res*);
extern  bool_t xdr_cl_calc_filter_req (XDR *, cl_calc_filter_req*);
extern  bool_t xdr_cl_calc_filter_req (XDR *, cl_calc_filter_req*);
extern  bool_t xdr_cl_calc_filter_res_t (XDR *, cl_calc_filter_res_t*);
extern  bool_t xdr_cl_calc_filter_res_t (XDR *, cl_calc_filter_res_t*);
extern  bool_t xdr_cl_calc_filter_res (XDR *, cl_calc_filter_res*);
extern  bool_t xdr_cl_calc_serial_req (XDR *, cl_calc_serial_req*);
extern  bool_t xdr_cl_calc_serial_req (XDR *, cl_calc_serial_req*);
extern  bool_t xdr_cl_calc_serial_res_t (XDR *, cl_calc_serial_res_t*);
extern  bool_t xdr_cl_calc_serial_res_t (XDR *, cl_calc_serial_res_t*);
extern  bool_t xdr_cl_calc_serial_res (XDR *, cl_calc_serial_res*);
extern  bool_t xdr_cl_calc_servo_req (XDR *, cl_calc_servo_req*);
extern  bool_t xdr_cl_calc_servo_req (XDR *, cl_calc_servo_req*);
extern  bool_t xdr_cl_calc_servo_res_t (XDR *, cl_calc_servo_res_t*);
extern  bool_t xdr_cl_calc_servo_res_t (XDR *, cl_calc_servo_res_t*);
extern  bool_t xdr_cl_calc_servo_res (XDR *, cl_calc_servo_res*);
extern  bool_t xdr_cl_calc_set_req (XDR *, cl_calc_set_req*);
extern  bool_t xdr_cl_calc_set_req (XDR *, cl_calc_set_req*);
extern  bool_t xdr_cl_calc_set_res_t (XDR *, cl_calc_set_res_t*);
extern  bool_t xdr_cl_calc_set_res_t (XDR *, cl_calc_set_res_t*);
extern  bool_t xdr_cl_calc_set_res (XDR *, cl_calc_set_res*);

#else /* K&R C */
extern bool_t xdr_cl_msg_t_s ();
extern bool_t xdr_cl_msg_t_s ();
extern bool_t xdr_cl_bus_t_s ();
extern bool_t xdr_cl_bus_t_s ();
extern bool_t xdr_cl_calc_freq_req ();
extern bool_t xdr_cl_calc_freq_req ();
extern bool_t xdr_cl_calc_freq_res_t ();
extern bool_t xdr_cl_calc_freq_res_t ();
extern bool_t xdr_cl_calc_freq_res ();
extern bool_t xdr_cl_calc_alert_req ();
extern bool_t xdr_cl_calc_alert_req ();
extern bool_t xdr_cl_calc_alert_res_t ();
extern bool_t xdr_cl_calc_alert_res_t ();
extern bool_t xdr_cl_calc_alert_res ();
extern bool_t xdr_cl_calc_read_req ();
extern bool_t xdr_cl_calc_read_req ();
extern bool_t xdr_cl_calc_read_res_t ();
extern bool_t xdr_cl_calc_read_res_t ();
extern bool_t xdr_cl_calc_read_res ();
extern bool_t xdr_cl_calc_write_req ();
extern bool_t xdr_cl_calc_write_req ();
extern bool_t xdr_cl_calc_write_res_t ();
extern bool_t xdr_cl_calc_write_res_t ();
extern bool_t xdr_cl_calc_write_res ();
extern bool_t xdr_cl_calc_timer_req ();
extern bool_t xdr_cl_calc_timer_req ();
extern bool_t xdr_cl_calc_timer_res_t ();
extern bool_t xdr_cl_calc_timer_res_t ();
extern bool_t xdr_cl_calc_timer_res ();
extern bool_t xdr_cl_calc_filter_req ();
extern bool_t xdr_cl_calc_filter_req ();
extern bool_t xdr_cl_calc_filter_res_t ();
extern bool_t xdr_cl_calc_filter_res_t ();
extern bool_t xdr_cl_calc_filter_res ();
extern bool_t xdr_cl_calc_serial_req ();
extern bool_t xdr_cl_calc_serial_req ();
extern bool_t xdr_cl_calc_serial_res_t ();
extern bool_t xdr_cl_calc_serial_res_t ();
extern bool_t xdr_cl_calc_serial_res ();
extern bool_t xdr_cl_calc_servo_req ();
extern bool_t xdr_cl_calc_servo_req ();
extern bool_t xdr_cl_calc_servo_res_t ();
extern bool_t xdr_cl_calc_servo_res_t ();
extern bool_t xdr_cl_calc_servo_res ();
extern bool_t xdr_cl_calc_set_req ();
extern bool_t xdr_cl_calc_set_req ();
extern bool_t xdr_cl_calc_set_res_t ();
extern bool_t xdr_cl_calc_set_res_t ();
extern bool_t xdr_cl_calc_set_res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CL_H_RPCGEN */
