/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "CL.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

cl_calc_freq_res *
cl_calc_freq_func_1(cl_calc_freq_req *argp, CLIENT *clnt)
{
	static cl_calc_freq_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CL_CALC_FREQ_FUNC,
		(xdrproc_t) xdr_cl_calc_freq_req, (caddr_t) argp,
		(xdrproc_t) xdr_cl_calc_freq_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

cl_calc_alert_res *
cl_calc_alert_func_1(cl_calc_alert_req *argp, CLIENT *clnt)
{
	static cl_calc_alert_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CL_CALC_ALERT_FUNC,
		(xdrproc_t) xdr_cl_calc_alert_req, (caddr_t) argp,
		(xdrproc_t) xdr_cl_calc_alert_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

cl_calc_read_res *
cl_calc_read_func_1(cl_calc_read_req *argp, CLIENT *clnt)
{
	static cl_calc_read_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CL_CALC_READ_FUNC,
		(xdrproc_t) xdr_cl_calc_read_req, (caddr_t) argp,
		(xdrproc_t) xdr_cl_calc_read_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

cl_calc_write_res *
cl_calc_write_func_1(cl_calc_write_req *argp, CLIENT *clnt)
{
	static cl_calc_write_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CL_CALC_WRITE_FUNC,
		(xdrproc_t) xdr_cl_calc_write_req, (caddr_t) argp,
		(xdrproc_t) xdr_cl_calc_write_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

cl_calc_timer_res *
cl_calc_timer_func_1(cl_calc_timer_req *argp, CLIENT *clnt)
{
	static cl_calc_timer_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CL_CALC_TIMER_FUNC,
		(xdrproc_t) xdr_cl_calc_timer_req, (caddr_t) argp,
		(xdrproc_t) xdr_cl_calc_timer_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

cl_calc_filter_res *
cl_calc_filter_func_1(cl_calc_filter_req *argp, CLIENT *clnt)
{
	static cl_calc_filter_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CL_CALC_FILTER_FUNC,
		(xdrproc_t) xdr_cl_calc_filter_req, (caddr_t) argp,
		(xdrproc_t) xdr_cl_calc_filter_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

cl_calc_serial_res *
cl_calc_serial_func_1(cl_calc_serial_req *argp, CLIENT *clnt)
{
	static cl_calc_serial_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CL_CALC_SERIAL_FUNC,
		(xdrproc_t) xdr_cl_calc_serial_req, (caddr_t) argp,
		(xdrproc_t) xdr_cl_calc_serial_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

cl_calc_servo_res *
cl_calc_servo_func_1(cl_calc_servo_req *argp, CLIENT *clnt)
{
	static cl_calc_servo_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CL_CALC_SERVO_FUNC,
		(xdrproc_t) xdr_cl_calc_servo_req, (caddr_t) argp,
		(xdrproc_t) xdr_cl_calc_servo_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

cl_calc_set_res *
cl_calc_set_func_1(cl_calc_set_req *argp, CLIENT *clnt)
{
	static cl_calc_set_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CL_CALC_SET_FUNC,
		(xdrproc_t) xdr_cl_calc_set_req, (caddr_t) argp,
		(xdrproc_t) xdr_cl_calc_set_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
