/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "CL.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
clprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		cl_calc_freq_req cl_calc_freq_func_1_arg;
		cl_calc_alert_req cl_calc_alert_func_1_arg;
		cl_calc_read_req cl_calc_read_func_1_arg;
		cl_calc_write_req cl_calc_write_func_1_arg;
		cl_calc_timer_req cl_calc_timer_func_1_arg;
		cl_calc_filter_req cl_calc_filter_func_1_arg;
		cl_calc_serial_req cl_calc_serial_func_1_arg;
		cl_calc_servo_req cl_calc_servo_func_1_arg;
		cl_calc_set_req cl_calc_set_func_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case CL_CALC_FREQ_FUNC:
		_xdr_argument = (xdrproc_t) xdr_cl_calc_freq_req;
		_xdr_result = (xdrproc_t) xdr_cl_calc_freq_res;
		local = (char *(*)(char *, struct svc_req *)) cl_calc_freq_func_1_svc;
		break;

	case CL_CALC_ALERT_FUNC:
		_xdr_argument = (xdrproc_t) xdr_cl_calc_alert_req;
		_xdr_result = (xdrproc_t) xdr_cl_calc_alert_res;
		local = (char *(*)(char *, struct svc_req *)) cl_calc_alert_func_1_svc;
		break;

	case CL_CALC_READ_FUNC:
		_xdr_argument = (xdrproc_t) xdr_cl_calc_read_req;
		_xdr_result = (xdrproc_t) xdr_cl_calc_read_res;
		local = (char *(*)(char *, struct svc_req *)) cl_calc_read_func_1_svc;
		break;

	case CL_CALC_WRITE_FUNC:
		_xdr_argument = (xdrproc_t) xdr_cl_calc_write_req;
		_xdr_result = (xdrproc_t) xdr_cl_calc_write_res;
		local = (char *(*)(char *, struct svc_req *)) cl_calc_write_func_1_svc;
		break;

	case CL_CALC_TIMER_FUNC:
		_xdr_argument = (xdrproc_t) xdr_cl_calc_timer_req;
		_xdr_result = (xdrproc_t) xdr_cl_calc_timer_res;
		local = (char *(*)(char *, struct svc_req *)) cl_calc_timer_func_1_svc;
		break;

	case CL_CALC_FILTER_FUNC:
		_xdr_argument = (xdrproc_t) xdr_cl_calc_filter_req;
		_xdr_result = (xdrproc_t) xdr_cl_calc_filter_res;
		local = (char *(*)(char *, struct svc_req *)) cl_calc_filter_func_1_svc;
		break;

	case CL_CALC_SERIAL_FUNC:
		_xdr_argument = (xdrproc_t) xdr_cl_calc_serial_req;
		_xdr_result = (xdrproc_t) xdr_cl_calc_serial_res;
		local = (char *(*)(char *, struct svc_req *)) cl_calc_serial_func_1_svc;
		break;

	case CL_CALC_SERVO_FUNC:
		_xdr_argument = (xdrproc_t) xdr_cl_calc_servo_req;
		_xdr_result = (xdrproc_t) xdr_cl_calc_servo_res;
		local = (char *(*)(char *, struct svc_req *)) cl_calc_servo_func_1_svc;
		break;

	case CL_CALC_SET_FUNC:
		_xdr_argument = (xdrproc_t) xdr_cl_calc_set_req;
		_xdr_result = (xdrproc_t) xdr_cl_calc_set_res;
		local = (char *(*)(char *, struct svc_req *)) cl_calc_set_func_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CLPROG, CLVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CLPROG, CLVERS, clprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CLPROG, CLVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CLPROG, CLVERS, clprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CLPROG, CLVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
